modLoader = "lowcodefml"
loaderVersion = "[1,)"
license = "MIT License"
showAsResourcePack = false

[[mods]]
modId = "handsoffvillagers"
version = "1.21.7-1.0.1"
displayName = "Hands Off, Villagers!"
displayURL = 'https://modrinth.com/user/spekarchik'
logoFile = "pack.png"
authors = "Sergey Pekarchik"
description = "Hands Off, Villagers! — stops villagers from picking up torchflower and pitcher seeds. Respect the seeds. Respect yourself."

[[dependencies.handsoffvillagers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.2,)"
ordering="NONE"
side = "BOTH"
